definitions:
  model.Request:
    properties:
      alias:
        type: string
      url:
        type: string
    required:
    - url
    type: object
info:
  contact: {}
  description: Сервис для сокращения ссылок
  title: Url-shortener
  version: 1.0.0
paths:
  /{alias}:
    get:
      description: Получает alias из URL, ищет соответствующий оригинальный URL и
        выполняет редирект (HTTP 302).
      parameters:
      - description: Alias для редиректа
        in: path
        name: alias
        required: true
        type: string
      responses:
        "302":
          description: Redirected to original URL
          schema:
            type: string
      summary: Перенаправляет на оригинальный URL по alias
      tags:
      - URL
  /url/{alias}:
    delete:
      description: Удаляет URL по alias. Возвращает статус 204 No Content в случае
        успеха.
      parameters:
      - description: Alias для удаления
        in: path
        name: alias
        required: true
        type: string
      responses:
        "204":
          description: URL успешно удалён
        "422":
          description: Alias не указан
          schema:
            type: string
        "500":
          description: Ошибка удаления URL
          schema:
            type: string
      summary: Удаляет URL
      tags:
      - URL
  /url/save:
    post:
      description: Сохраняет оригинальный URL и возвращает alias. Если alias не передан,
        генерируется случайный.
      parameters:
      - description: Данные запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Request'
      responses:
        "201":
          description: URL успешно сохранён
          schema:
            type: string
        "400":
          description: Некорректный JSON
          schema:
            type: string
        "422":
          description: Ошибка валидации запроса
          schema:
            type: string
        "500":
          description: Ошибка сохранения URL
          schema:
            type: string
      summary: Сохраняет URL
      tags:
      - URL
swagger: "2.0"
